# Setup
title:               Florent Fettu
tagline:             'Data Scientist'
description:         'I am Florent Fettu, an aspiring data scientist. Feel free to contact me.'
url:                 https://florentfettu.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Florent Fettu
  url:               https://www.linkedin.com/in/florentfettu/
  email:             florent.fettu@hec.ca

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
